language: node_js
node_js:
- '12'


addons:
  chrome: stable


before_install:
- npm install -g @angular/cli
install: npm install

script:
  - npm run test --watch=false --browsers=ChromeHeadlessNoSandbox
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

branches:
  only:
  - feature/Travis_tests  
deploy:
  provider: heroku
  app: real-super-cool-modern-app-wfh
  api_key:
    secure: e4v93i5CH3dTOaQApBsCVXum4gHmxqUZdnhprUPhy8DmDqOXSbsjjc94hNJxI57uYhCS1GcWF0v4SigVZAIk/YItLe8lQydoG4DZPGAmimkGvuy7Iw7iPJvIw04rKXJFq7Xl9b5I060TRJojuSOOcJgiYRfJ+OHTgtv+3qVcSbeB7pWHHCj+wu9eFMj9zgNWnxvciHflb8GLEDStOHPPi7KwFv7AVuO0fecICTQpfdNZca4/ekYEbRk029OBAv9uErai0Tospz3g7419lmJDTmFUla/x7+Lsdivf/Y5OAGYuSk72HQNCBSFm3uMfgKgr8520VKtqrkyj+lqDn1o3HblQeA5m+abo+6HpxgzoQLRuE2D3c3bqlsPwvH4R38yoOH1QkTADN+k6/Uc0Tj7T5ZXZITOmG+YHnaT4ngk/6Z+LRl/JCYOqxQa4pJ+olX8J6dH8b9dthKSX4yP9tckk8IYoKC2UfOP0oUTme4h+Azi3qkcTbDxg49NYKLLxlS/+EIwPVeOEIqac0lOyjwSbWj5AWh0MSuW/cqRdV5KVRx0ByQaHscJjqQZVsmpVK3LzH7NVjwiYfcpLZnlLLG7woUs5khr1r2+twRRy10UyF/ZSWNlBLDZS701Gbq80yC3NCgyAjJ7VzD8WkksAj4XfcFt8acWejm3oiZe0s61wGYQ=
